version: '3.8'

services:
  # Ollama service for local LLM inference
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ../ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    # For GPU support (uncomment if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Model initialization service
  model-init:
    image: curlimages/curl:latest
    container_name: model-init
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ../scripts/init-models.sh:/init-models.sh:ro
    command: ["/bin/sh", "/init-models.sh"]
    restart: "no"
    networks:
      - default

  # RAG Pipeline API
  rag-pipeline:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: rag-pipeline
    ports:
      - "8000:8000"
    volumes:
      - feast_data:/app/feast_feature_repo/data
      - ../sample_docs:/app/sample_docs
      - ../logs:/app/logs
      - ../static:/app/static
    environment:
      # Feast RAG Pipeline configuration
      - RAG_API_HOST=0.0.0.0
      - RAG_API_PORT=8000
      - RAG_OLLAMA_HOST=ollama
      - RAG_OLLAMA_PORT=11434
      - RAG_FEAST_REPO_PATH=/app/feast_feature_repo
      - RAG_MILVUS_URI=/app/feast_feature_repo/data/online_store.db
      - RAG_LOG_LEVEL=INFO
      - RAG_DEBUG_MODE=false
      - RAG_ENABLE_CORS=true
      - RAG_MAX_FILE_SIZE=104857600  # 100MB
    depends_on:
      model-init:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - cache

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
    depends_on:
      - rag-pipeline
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:
  ollama_data:
  feast_data:

networks:
  default:
    name: rag-network
